collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7234042
  brandStrength: 0.393617
  lightness: 0.5340425
  brandColors:
    - '#C9FFFF'
    - '#7FD0FF'
    - '#2B87CF'
    - '#040402'
    - '#374B00'
  rhythmicContrast: 0.5436404
typography_spectrum: 0.03373036
layout_spectrum: 0.9851064
name: SV Blueys
